-- MySQL Script generated by MySQL Workbench
-- Tue Dec  6 18:01:20 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Resort`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Resort` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Resort` (
  `MountainID` INT NOT NULL,
  `mountainName` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `elevation` INT NULL,
  PRIMARY KEY (`MountainID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Difficulty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Difficulty` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Difficulty` (
  `rating` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`rating`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BackcountryTerrain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BackcountryTerrain` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BackcountryTerrain` (
  `idBackcountryTerrain` INT NOT NULL,
  `backcountryTerainName` VARCHAR(45) NULL,
  `backcountryGate` TINYINT(1) NULL,
  PRIMARY KEY (`idBackcountryTerrain`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Runs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Runs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Runs` (
  `RunID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `difficulty` VARCHAR(45) NULL,
  `map` VARCHAR(45) NULL,
  `MountainID` INT NOT NULL,
  `medical` VARCHAR(45) NULL,
  `difficulty_rating` INT NOT NULL,
  `BackcountryTerrain_idBackcountryTerrain` INT NOT NULL,
  PRIMARY KEY (`RunID`),
  INDEX `fk_Runs_Mountain_idx` (`MountainID` ASC),
  INDEX `fk_Runs_difficulty1_idx` (`difficulty_rating` ASC),
  INDEX `fk_Runs_BackcountryTerrain1_idx` (`BackcountryTerrain_idBackcountryTerrain` ASC),
  CONSTRAINT `fk_Runs_Mountain`
    FOREIGN KEY (`MountainID`)
    REFERENCES `mydb`.`Resort` (`MountainID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Runs_difficulty1`
    FOREIGN KEY (`difficulty_rating`)
    REFERENCES `mydb`.`Difficulty` (`rating`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Runs_BackcountryTerrain1`
    FOREIGN KEY (`BackcountryTerrain_idBackcountryTerrain`)
    REFERENCES `mydb`.`BackcountryTerrain` (`idBackcountryTerrain`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Terrain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Terrain` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Terrain` (
  `terrainID` INT NOT NULL,
  `terrainName` VARCHAR(45) NULL,
  `Resort_MountainID` INT NOT NULL,
  `BackcountryTerrain_idBackcountryTerrain` INT NOT NULL,
  PRIMARY KEY (`terrainID`),
  INDEX `fk_Terrain_Resort1_idx` (`Resort_MountainID` ASC),
  INDEX `fk_Terrain_BackcountryTerrain1_idx` (`BackcountryTerrain_idBackcountryTerrain` ASC),
  CONSTRAINT `fk_Terrain_Resort1`
    FOREIGN KEY (`Resort_MountainID`)
    REFERENCES `mydb`.`Resort` (`MountainID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terrain_BackcountryTerrain1`
    FOREIGN KEY (`BackcountryTerrain_idBackcountryTerrain`)
    REFERENCES `mydb`.`BackcountryTerrain` (`idBackcountryTerrain`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chairlift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Chairlift` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Chairlift` (
  `chiarliftID` INT NOT NULL,
  `chairliftName` VARCHAR(45) NULL,
  `ChairLiftDirection_idChairLiftDirection` INT NOT NULL,
  `Terrain_terrainID` INT NOT NULL,
  PRIMARY KEY (`chiarliftID`),
  INDEX `fk_Chairlift_Terrain1_idx` (`Terrain_terrainID` ASC),
  CONSTRAINT `fk_Chairlift_Terrain1`
    FOREIGN KEY (`Terrain_terrainID`)
    REFERENCES `mydb`.`Terrain` (`terrainID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Snowmaking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Snowmaking` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Snowmaking` (
  `snowMachineID` INT NOT NULL,
  `make` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `modelYear` INT NULL,
  `yearAquired` VARCHAR(45) NULL,
  PRIMARY KEY (`snowMachineID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Snowmaking_has_Runs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Snowmaking_has_Runs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Snowmaking_has_Runs` (
  `Snowmaking_snowMachineID` INT NOT NULL,
  `Runs_RunID` INT NOT NULL,
  PRIMARY KEY (`Snowmaking_snowMachineID`, `Runs_RunID`),
  INDEX `fk_Snowmaking_has_Runs_Runs1_idx` (`Runs_RunID` ASC),
  INDEX `fk_Snowmaking_has_Runs_Snowmaking1_idx` (`Snowmaking_snowMachineID` ASC),
  CONSTRAINT `fk_Snowmaking_has_Runs_Snowmaking1`
    FOREIGN KEY (`Snowmaking_snowMachineID`)
    REFERENCES `mydb`.`Snowmaking` (`snowMachineID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Snowmaking_has_Runs_Runs1`
    FOREIGN KEY (`Runs_RunID`)
    REFERENCES `mydb`.`Runs` (`RunID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Terrain_has_Snowmaking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Terrain_has_Snowmaking` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Terrain_has_Snowmaking` (
  `Terrain_terrainID` INT NOT NULL,
  `Snowmaking_snowMachineID` INT NOT NULL,
  PRIMARY KEY (`Terrain_terrainID`, `Snowmaking_snowMachineID`),
  INDEX `fk_Terrain_has_Snowmaking_Snowmaking1_idx` (`Snowmaking_snowMachineID` ASC),
  INDEX `fk_Terrain_has_Snowmaking_Terrain1_idx` (`Terrain_terrainID` ASC),
  CONSTRAINT `fk_Terrain_has_Snowmaking_Terrain1`
    FOREIGN KEY (`Terrain_terrainID`)
    REFERENCES `mydb`.`Terrain` (`terrainID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terrain_has_Snowmaking_Snowmaking1`
    FOREIGN KEY (`Snowmaking_snowMachineID`)
    REFERENCES `mydb`.`Snowmaking` (`snowMachineID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Runs_has_Chairlift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Runs_has_Chairlift` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Runs_has_Chairlift` (
  `Runs_RunID` INT NOT NULL,
  `Chairlift_chiarliftID` INT NOT NULL,
  PRIMARY KEY (`Runs_RunID`, `Chairlift_chiarliftID`),
  INDEX `fk_Runs_has_Chairlift_Chairlift1_idx` (`Chairlift_chiarliftID` ASC),
  INDEX `fk_Runs_has_Chairlift_Runs1_idx` (`Runs_RunID` ASC),
  CONSTRAINT `fk_Runs_has_Chairlift_Runs1`
    FOREIGN KEY (`Runs_RunID`)
    REFERENCES `mydb`.`Runs` (`RunID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Runs_has_Chairlift_Chairlift1`
    FOREIGN KEY (`Chairlift_chiarliftID`)
    REFERENCES `mydb`.`Chairlift` (`chiarliftID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view1` ;
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
